sudo: false
language: ruby
cache: bundler
bundler_args: --without production
before_install:
    - gem update --system
services:
    - mongodb
before_script:
    - sleep 15
    - mongo mydb_test --eval 'db.addUser("travis", "test");'
